qml_module(selestis-config
    URI Selestis.Config
    INCLUDE_PREFIX config
    SOURCES
        common.cpp
        rootnodes.cpp
        configattached.cpp
        appearanceconfig.cpp
        borderconfig.cpp
        font.cpp
        fontbuilder.cpp
        tokensattached.cpp
        anim.cpp
        enums.hpp
        backgroundconfig.hpp
        barconfig.hpp
        dashboardconfig.hpp
        generalconfig.hpp
        launcherconfig.hpp
        lockconfig.hpp
        nexusconfig.hpp
        notifsconfig.hpp
        osdconfig.hpp
        serviceconfig.hpp
        sessionconfig.hpp
        sidebarconfig.hpp
        userpaths.hpp
        utilitiesconfig.hpp
        tokens.hpp
    LIBRARIES
        Qt::Quick
        Qt::QuickControls2
    DEPENDENCIES
        Selestis.Settings
)
target_link_libraries(selestis-config PUBLIC
    Qt::Gui
    selestis-util
    selestis-core
    selestis-settings
)
